site_name: CartER

nav:
  - 'index.md'

  - Development:
    - 'development/index.md'
    - 'development/further_work.md'

  - Assembly:
    - 'assembly/index.md'
    - 'assembly/bom.md'
    - 'assembly/cad.md'
    - 'assembly/components.md'

  - Articles:
    - 'articles/index.md'
    - 'articles/handover_v1.md'
    - 'articles/presentation.md'


  - Videos:
    - 'videos/index.md'
    - 'videos/automated_PID_setup.md'

theme:
  name: material

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_url: https://github.com/ANOsapien/CartER

plugins:
  - search:
      lang: en
  - mkdocs-video

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - admonition
  - toc:
      permalink: true

extra_javascript:
  - extra/js/mathjax_config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - extra/css/image_alignment.css
