name: ci

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache pip
        uses: actions/cache@v4
        with:
          key: mkdocs-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          path: ~/.cache/pip
          restore-keys: |
            mkdocs-${{ runner.os }}-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs-material mkdocs-video pymdown-extensions

          

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
