name: Deploy MkDocs site

on:
  push:
    branches:
      - main  # or master, whichever your repo uses

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-video pymdown-extensions

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
